DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(ID INT PRIMARY KEY,
                  NAME VARCHAR(255));

INSERT INTO ACCOUNT VALUES(1, 'Alice');

INSERT INTO ACCOUNT VALUES(2, 'Bob');

-- SELECT * FROM TEST ORDER BY ID;
-- UPDATE TEST SET NAME='Charlie' WHERE ID=1;
-- DELETE FROM TEST WHERE ID=2;